apiVersion: v1
kind: Service
metadata:
  name: align-backend-svc
  labels:
    app: align
    tier: api
spec:
  type: ClusterIP
  selector:
    app: align
    tier: api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
